"""Render an ``AnalysisResult`` into a one-page Markdown (or HTML) report.

The report leads with the decision and a traffic-light banner, then shows the
supporting evidence in the same order the decision engine used it, so a reader
can audit the recommendation top-to-bottom.
"""

from __future__ import annotations

from .pipeline import AnalysisResult
from .decision import Decision

_BADGE = {
    Decision.SHIP: ("✅", "SHIP"),
    Decision.DO_NOT_SHIP: ("⛔", "DO NOT SHIP"),
    Decision.CONTINUE: ("⏳", "CONTINUE TESTING"),
}


def build_report(result: AnalysisResult) -> str:
    """Return a Markdown experiment report for ``result``."""
    d = result.decision
    emoji, label = _BADGE[d.decision]
    lines: list[str] = []

    lines.append(f"# ExperimentGuard Report — `{result.experiment_id}`")
    lines.append("")
    lines.append(f"## {emoji} Decision: **{label}**")
    lines.append("")
    for reason in d.reasons:
        lines.append(f"- {reason}")
    lines.append("")

    # Data validity
    v = result.validation
    lines.append("## 1. Data validity")
    lines.append("")
    lines.append(f"- Rows: {v.n_rows:,} · Users: {v.n_users:,} · Arms: {', '.join(v.arms)}")
    lines.append(f"- {result.srm.summary()}")
    if v.warnings:
        lines.append("- Warnings: " + "; ".join(v.warnings))
    lines.append("")

    # Power
    p = result.power
    lines.append("## 2. Power & sample size")
    lines.append("")
    lines.append(
        f"- To detect an absolute MDE of {p.mde_absolute:.4f} "
        f"({p.mde_relative * 100:.1f}% relative) at α={p.alpha}, power={p.power}: "
        f"**{p.per_arm_sample_size:,} users/arm** ({p.total_sample_size:,} total)."
    )
    lines.append("")

    # Primary metric
    c = result.conversion
    lines.append("## 3. Primary metric — conversion")
    lines.append("")
    lines.append(f"- {c.summary()}")
    lines.append(
        f"- Control {c.control_rate:.4f} (n={c.control_n:,}) · "
        f"Variant {c.variant_rate:.4f} (n={c.variant_n:,})"
    )
    lines.append("")

    # Value
    b = result.bootstrap
    lines.append("## 4. Transaction-value uplift (bootstrap)")
    lines.append("")
    lines.append(f"- {b.summary()}")
    lines.append(f"- {b.n_resamples:,} resamples, percentile method")
    lines.append("")

    # Guardrails
    g = result.guardrails
    lines.append("## 5. Guardrails")
    lines.append("")
    lines.append(f"- {g.summary()}")
    ps = g.details.get("payment_success", {})
    la = g.details.get("latency", {})
    if ps:
        lines.append(
            f"- Payment success: {ps['control_rate']:.4f} -> {ps['variant_rate']:.4f} "
            f"(drop {ps['absolute_drop']:+.4f}, p={ps['p_value']:.3g})"
        )
    if la:
        lines.append(
            f"- Latency mean: {la['control_mean_ms']:.1f}ms -> {la['variant_mean_ms']:.1f}ms "
            f"({la['relative_increase'] * 100:+.1f}%, p95 "
            f"{la['control_p95_ms']:.0f}->{la['variant_p95_ms']:.0f}ms)"
        )
    lines.append("")

    # Segments
    lines.append("## 6. Segment analysis (BH-corrected)")
    lines.append("")
    for seg in result.segments:
        lines.append(f"- **{seg.dimension}**: {seg.summary()}")
    if not result.segments:
        lines.append("- (no segment dimensions available)")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by ExperimentGuard. Decision precedence: "
                 "data validity → guardrails → primary effect → power.*")
    return "\n".join(lines)


def build_html_report(result: AnalysisResult) -> str:
    """Wrap the Markdown report in a minimal, self-contained HTML page.

    Kept dependency-free (no Markdown library): headings and bullets are
    converted with a tiny inline transformer so the file renders anywhere.
    """
    md = build_report(result)
    body: list[str] = []
    in_list = False
    for raw in md.split("\n"):
        line = raw.rstrip()
        if line.startswith("### "):
            if in_list:
                body.append("</ul>"); in_list = False
            body.append(f"<h3>{_esc(line[4:])}</h3>")
        elif line.startswith("## "):
            if in_list:
                body.append("</ul>"); in_list = False
            body.append(f"<h2>{_esc(line[3:])}</h2>")
        elif line.startswith("# "):
            if in_list:
                body.append("</ul>"); in_list = False
            body.append(f"<h1>{_esc(line[2:])}</h1>")
        elif line.startswith("- "):
            if not in_list:
                body.append("<ul>"); in_list = True
            body.append(f"<li>{_inline(line[2:])}</li>")
        elif line == "---":
            if in_list:
                body.append("</ul>"); in_list = False
            body.append("<hr>")
        elif line == "":
            if in_list:
                body.append("</ul>"); in_list = False
        else:
            body.append(f"<p>{_inline(line)}</p>")
    if in_list:
        body.append("</ul>")

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ExperimentGuard — {_esc(result.experiment_id)}</title>
<style>
  body {{ font-family: system-ui, sans-serif; max-width: 760px; margin: 2rem auto;
         padding: 0 1rem; line-height: 1.55; color: #1a1a1a; }}
  h1 {{ font-size: 1.6rem; }} h2 {{ margin-top: 1.8rem; font-size: 1.15rem;
       border-bottom: 1px solid #eee; padding-bottom: .3rem; }}
  code {{ background: #f4f4f5; padding: .1rem .3rem; border-radius: 4px; }}
  li {{ margin: .2rem 0; }} hr {{ border: none; border-top: 1px solid #eee; }}
</style></head><body>
{chr(10).join(body)}
</body></html>"""


def _esc(text: str) -> str:
    return (text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def _inline(text: str) -> str:
    """Escape, then apply minimal `code` and **bold** inline formatting."""
    out = _esc(text)
    # Bold: **...**
    while "**" in out:
        out = out.replace("**", "<strong>", 1).replace("**", "</strong>", 1)
    # Inline code: `...`
    while "`" in out:
        out = out.replace("`", "<code>", 1).replace("`", "</code>", 1)
    return out
